name: Analyse SonarQube et Envoi d'Email

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    
  # workflow_run:
  #   workflows: ["wallet-msir-jour-groupe2"]
  #   types:
  #     - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Configuration de Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Remplacez par la version de Java que vous souhaitez utiliser

    - name: Construction avec Maven
      run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

    - name: Analyse SonarQube
      run: mvn sonar:sonar -Dsonar.host.url=$SONAR_URL

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Approuver le Déploiement
      run: echo "Déploiement en cours sur le serveur"

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Envoyer un Email en cas de Succès
      if: success()
      run: |
        echo "L'analyse a réussi. Aucune action supplémentaire n'est requise."
        echo "URL du Build: ${{ github.run_url }}"
      env:
        RECIPIENT_EMAIL: "netrathior@gmail.com,moussa3.thior@ucad.edu.sn,netrathiorpa@gmail.com"
      # Ajoutez la logique pour envoyer une notification par e-mail en cas de succès

    - name: Envoyer un Email en cas d'Échec
      if: failure()
      run: |
        echo "L'analyse a échoué. Veuillez enquêter et prendre les mesures nécessaires."
        echo "URL du Build: ${{ github.run_url }}"
      env:
        RECIPIENT_EMAIL: "netrathior@gmail.com,moussa3.thior@ucad.edu.sn,netrathiorpa@gmail.com"
      # Ajoutez la logique pour envoyer une notification par e-mail en cas d'échec
